# Generated by Django 4.2.7 on 2023-12-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_orderdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
